[package]
name = "clippyboard-select"
version = "0.1.0"
edition = "2024"

[dependencies]
clippyboard-shared = { path = "../clippyboard-shared" }
ciborium.workspace = true
eframe = "0.32.2"
egui_extras = { version = "0.32.2", features = ["image"] }
eyre.workspace = true
serde.workspace = true
